import {render,screen,waitFor} from '@testing-library/react';import userEvent from '@testing-library/user-event';import {axe} from 'jest-axe';import {describe,expect,it,vi} from 'vitest';import {TaskForm} from './TaskForm';import {task} from '../test/factories';
describe('TaskForm',()=>{
  it('renderiza criação acessível, foca título e fecha por ações',async()=>{const close=vi.fn();const{container}=render(<TaskForm task={null} onClose={close} onSave={vi.fn()}/>);expect(screen.getByRole('dialog',{name:'Nova tarefa'})).toBeInTheDocument();expect(screen.getByLabelText('Título')).toHaveFocus();expect(screen.getByLabelText('Título')).toHaveAttribute('maxlength','160');expect(screen.getByLabelText('Categoria')).toBeRequired();expect(screen.getByLabelText('Prazo')).toBeRequired();expect(await axe(container)).toHaveNoViolations();await userEvent.click(screen.getByRole('button',{name:'Cancelar'}));expect(close).toHaveBeenCalledOnce()});
  it('fecha por Escape, botão e backdrop',async()=>{const close=vi.fn();const{container,rerender}=render(<TaskForm task={null} onClose={close} onSave={vi.fn()}/>);await userEvent.keyboard('{Escape}');expect(close).toHaveBeenCalledOnce();await userEvent.click(screen.getByRole('button',{name:'Fechar formulário'}));expect(close).toHaveBeenCalledTimes(2);rerender(<TaskForm task={null} onClose={close} onSave={vi.fn()}/>);await userEvent.click(container.querySelector('.modal-backdrop')!);expect(close).toHaveBeenCalledTimes(3)});
  it('impede envio nativo inválido',async()=>{const save=vi.fn();render(<TaskForm task={null} onClose={vi.fn()} onSave={save}/>);await userEvent.clear(screen.getByLabelText('Título'));await userEvent.click(screen.getByRole('button',{name:'Salvar tarefa'}));expect(save).not.toHaveBeenCalled()});
  it('envia criação com todos os campos',async()=>{const save=vi.fn().mockResolvedValue(undefined),close=vi.fn();render(<TaskForm task={null} onClose={close} onSave={save}/>);await userEvent.type(screen.getByLabelText('Título'),'Prova');await userEvent.type(screen.getByLabelText('Categoria'),'Cálculo');await userEvent.type(screen.getByLabelText('Responsável'),'Ada');await userEvent.clear(screen.getByLabelText('Prazo'));await userEvent.type(screen.getByLabelText('Prazo'),'2026-09-20');await userEvent.selectOptions(screen.getByLabelText('Prioridade'),'URGENT');await userEvent.selectOptions(screen.getByLabelText('Status'),'COMPLETED');await userEvent.type(screen.getByLabelText('Descrição'),'Capítulos 1–4');await userEvent.click(screen.getByRole('button',{name:'Salvar tarefa'}));await waitFor(()=>expect(save).toHaveBeenCalledWith(expect.objectContaining({title:'Prova',category:'Cálculo',responsible:'Ada',due_date:'2026-09-20',priority:'URGENT',status:'COMPLETED',description:'Capítulos 1–4'})));expect(close).toHaveBeenCalledOnce()});
  it('preenche edição e exibe falha sem fechar',async()=>{const save=vi.fn().mockRejectedValue(new Error('Falha no PATCH')),close=vi.fn();render(<TaskForm task={task({title:'Antiga',status:'COMPLETED',priority:'HIGH'})} onClose={close} onSave={save}/>);expect(screen.getByLabelText('Título')).toHaveValue('Antiga');expect(screen.getByLabelText('Status')).toHaveValue('COMPLETED');await userEvent.clear(screen.getByLabelText('Título'));await userEvent.type(screen.getByLabelText('Título'),'Nova');await userEvent.click(screen.getByRole('button',{name:'Salvar tarefa'}));expect(await screen.findByRole('alert')).toHaveTextContent('Falha no PATCH');expect(close).not.toHaveBeenCalled()});
  it('bloqueia duplo submit enquanto aguarda',async()=>{let release!:()=>void;const save=vi.fn(()=>new Promise<void>(resolve=>{release=resolve}));render(<TaskForm task={task()} onClose={vi.fn()} onSave={save}/>);const button=screen.getByRole('button',{name:'Salvar tarefa'});await userEvent.dblClick(button);expect(save).toHaveBeenCalledOnce();expect(screen.getByRole('button',{name:'Salvando…'})).toBeDisabled();release();await waitFor(()=>expect(button).not.toBeDisabled())});
});
