import {beforeEach,describe,expect,it,vi} from 'vitest';import {api,ApiError,request} from './api';
const response=(status:number,body:unknown=null)=>({ok:status>=200&&status<300,status,json:vi.fn().mockResolvedValue(body)}) as unknown as Response;
describe('api HTTP',()=>{
  beforeEach(()=>vi.stubGlobal('fetch',vi.fn()));
  it.each([200,201])('retorna JSON em HTTP %s',async status=>{vi.mocked(fetch).mockResolvedValue(response(status,{id:1}));await expect(request('/ok')).resolves.toEqual({id:1});expect(fetch).toHaveBeenCalledWith('/api/ok',expect.objectContaining({credentials:'include',headers:{'Content-Type':'application/json'}}))});
  it('trata 204 sem tentar ler JSON',async()=>{const result=response(204);vi.mocked(fetch).mockResolvedValue(result);await expect(api.logout()).resolves.toBeUndefined();expect(result.json).not.toHaveBeenCalled()});
  it.each([400,401,403,404,409,422,500])('transforma HTTP %s em ApiError',async status=>{vi.mocked(fetch).mockResolvedValue(response(status,{detail:`erro ${status}`}));await expect(request('/fail')).rejects.toEqual(new ApiError(`erro ${status}`,status))});
  it('usa fallback para corpo inválido e detail inesperado',async()=>{const bad={ok:false,status:500,json:vi.fn().mockRejectedValue(new Error('bad'))} as unknown as Response;vi.mocked(fetch).mockResolvedValueOnce(bad);await expect(request('/bad')).rejects.toThrow('Erro inesperado');vi.mocked(fetch).mockResolvedValueOnce(response(500,{detail:{private:'stack'}}));await expect(request('/bad')).rejects.toThrow('Erro inesperado')});
  it('emite expiração em 401 privado, mas não no bootstrap de sessão',async()=>{const listener=vi.fn();window.addEventListener('taskflow:unauthorized',listener);vi.mocked(fetch).mockResolvedValue(response(401,{detail:'expirada'}));await expect(request('/tasks')).rejects.toThrow();expect(listener).toHaveBeenCalledOnce();await expect(request('/auth/me')).rejects.toThrow();expect(listener).toHaveBeenCalledOnce()});
  it('serializa login e cadastro sem inventar role',async()=>{vi.mocked(fetch).mockResolvedValue(response(200,{}));await api.login('a@b.com','secret123');await api.registerMember({name:'Ana',email:'a@b.com',invite_code:'x'.repeat(32),password:'secret123',password_confirmation:'secret123'});const calls=vi.mocked(fetch).mock.calls;expect(calls[0][1]).toMatchObject({method:'POST',body:JSON.stringify({email:'a@b.com',password:'secret123'})});expect(JSON.parse(String(calls[1][1]?.body))).not.toHaveProperty('role')});
  it('monta os métodos de tarefas corretamente',async()=>{vi.mocked(fetch).mockResolvedValue(response(200,{}));const data={title:'T',description:null,category:'C',responsible:null,due_date:'2026-09-20',priority:'HIGH' as const,status:'PENDING' as const};await api.me();await api.tasks('?upcoming=true');await api.summary();await api.create(data);await api.update(7,{status:'COMPLETED'});vi.mocked(fetch).mockResolvedValueOnce(response(204));await api.remove(7);expect(vi.mocked(fetch).mock.calls.map(call=>[call[0],call[1]?.method])).toEqual([['/api/auth/me',undefined],['/api/tasks?upcoming=true',undefined],['/api/dashboard/summary',undefined],['/api/tasks','POST'],['/api/tasks/7','PATCH'],['/api/tasks/7','DELETE']])});
});
