import {useCallback,useEffect,useState} from 'react';
import {CalendarSync,CheckCircle2,Cloud,Link2,Plus,RefreshCw,Trash2,Unplug} from 'lucide-react';
import {api} from '../services/api';
import type {GoogleCalendarItem,GoogleCalendarStatus,GoogleSourceInput,GoogleSyncResult} from '../types';

const blank:GoogleSourceInput={calendar_id:'',subject_name:'',professor_name:'',enabled:true};

export function GoogleCalendarIntegration(){
  const[status,setStatus]=useState<GoogleCalendarStatus|null>(null);const[calendars,setCalendars]=useState<GoogleCalendarItem[]>([]);const[form,setForm]=useState(blank);const[busy,setBusy]=useState('');const[error,setError]=useState('');const[notice,setNotice]=useState('');
  const load=useCallback(async()=>{try{const current=await api.googleStatus();setStatus(current);if(current.connected)setCalendars(await api.googleCalendars())}catch(err){setError(err instanceof Error?err.message:'Falha ao carregar integração')}},[]);
  // A montagem da página sincroniza o estado administrativo com a API.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{void load()},[load]);
  const run=async(label:string,action:()=>Promise<unknown>)=>{setBusy(label);setError('');setNotice('');try{await action();await load()}catch(err){setError(err instanceof Error?err.message:'Falha na integração')}finally{setBusy('')}};
  const connect=()=>run('connect',async()=>{const result=await api.googleConnect();location.assign(result.authorization_url)});
  const create=async(event:React.FormEvent)=>{event.preventDefault();await run('create',async()=>{await api.googleCreateSource(form);setForm(blank);setNotice('Calendário adicionado como fonte do TaskFlow.')})};
  const sync=(sourceId?:number)=>run(`sync-${sourceId??'all'}`,async()=>{const result:GoogleSyncResult=await api.googleSync(sourceId);setNotice(`${result.created} criada(s), ${result.updated} atualizada(s), ${result.deleted} removida(s).`) });
  return <section className="integration-page">
    <div className="integration-hero"><div><span className="kicker"><Cloud/> Fonte externa</span><h2>Google Calendar</h2><p>Importe atividades somente dos calendários escolhidos. Alunos nunca conectam contas próprias.</p></div><div className={`connection-pill ${status?.connected?'connected':''}`}><i/>{status?.connected?'Conectado':'Desconectado'}</div></div>
    {error&&<div className="error-banner" role="alert">{error}<button onClick={()=>setError('')}>×</button></div>}{notice&&<div className="success-banner"><CheckCircle2/>{notice}</div>}
    {!status?.configured?<article className="integration-setup"><Link2/><div><h3>Configuração externa necessária</h3><p>Preencha as variáveis Google no arquivo <code>backend/.env</code> antes de conectar.</p></div></article>:!status.connected?<article className="connect-card"><CalendarSync/><div><span className="eyebrow">Somente administrador</span><h3>Conecte o calendário da turma</h3><p>O TaskFlow solicitará somente permissão de leitura.</p></div><button className="button button-ink" disabled={busy==='connect'} onClick={connect}>{busy==='connect'?'Abrindo Google…':'Conectar Google Calendar'}</button></article>:<>
      <div className="integration-toolbar"><div><span className="eyebrow">Conta conectada</span><strong>{status.account_email}</strong></div><button className="button button-small button-sun" disabled={busy.startsWith('sync')} onClick={()=>sync()}><RefreshCw/> Sincronizar agora</button><button className="integration-danger" disabled={busy==='disconnect'} onClick={()=>confirm('Desconectar o Google Calendar?')&&run('disconnect',api.googleDisconnect)}><Unplug/> Desconectar</button></div>
      <div className="integration-grid"><form className="source-form" onSubmit={create}><span className="eyebrow">Nova fonte</span><h3>Escolha um calendário</h3><label>Calendário<select required value={form.calendar_id} onChange={e=>setForm({...form,calendar_id:e.target.value})}><option value="">Selecione…</option>{calendars.map(item=><option value={item.id} key={item.id}>{item.name}{item.primary?' (principal)':''}</option>)}</select></label><label>Matéria / categoria<input required maxLength={80} value={form.subject_name} onChange={e=>setForm({...form,subject_name:e.target.value})} placeholder="Ex.: Cálculo I"/></label><label>Professor<input maxLength={100} value={form.professor_name} onChange={e=>setForm({...form,professor_name:e.target.value})} placeholder="Opcional"/></label><button className="button button-ink" disabled={busy==='create'}><Plus/> Adicionar fonte</button></form><div className="source-list"><span className="eyebrow">Calendários selecionados</span><h3>{status.sources.length} fonte(s) ativa(s)</h3>{status.sources.length?status.sources.map(source=><article className="source-card" key={source.id}><div><CalendarSync/><span><b>{source.calendar_name}</b><small>{source.subject_name}{source.professor_name?` · ${source.professor_name}`:''}</small></span></div><div className="source-meta"><span>{source.last_synced_at?`Última sync: ${new Date(source.last_synced_at).toLocaleString('pt-BR')}`:'Ainda não sincronizado'}</span>{source.last_error&&<em>{source.last_error}</em>}</div><div className="source-actions"><button aria-label={source.enabled?'Desativar fonte':'Ativar fonte'} onClick={()=>run(`toggle-${source.id}`,()=>api.googleUpdateSource(source.id,{enabled:!source.enabled}))}><span className={`switch ${source.enabled?'on':''}`}><i/></span>{source.enabled?'Ativa':'Inativa'}</button><button aria-label="Sincronizar fonte" onClick={()=>sync(source.id)}><RefreshCw/></button><button aria-label="Excluir fonte" onClick={()=>confirm('Remover esta fonte?')&&run(`delete-${source.id}`,()=>api.googleDeleteSource(source.id))}><Trash2/></button></div></article>):<div className="source-empty">Selecione ao lado quais calendários realmente pertencem à turma.</div>}</div></div>
    </>}
  </section>;
}
