import {render,screen,waitFor,within} from '@testing-library/react';import userEvent from '@testing-library/user-event';import {axe} from 'jest-axe';import {beforeEach,describe,expect,it,vi} from 'vitest';import App from './App';import {api,ApiError} from './services/api';import {admin,member,summary,task} from './test/factories';import type {Task,User} from './types';
vi.mock('./pages/GoogleCalendarIntegration',()=>({GoogleCalendarIntegration:()=> <div>Integração administrativa Google</div>}));
const tasks=[task({id:1,title:'Cálculo',due_date:'2026-09-20'}),task({id:2,title:'Python',category:'Programação',due_date:'2026-09-20',priority:'HIGH'}),task({id:3,title:'Álgebra',due_date:'2026-10-05',status:'COMPLETED'})];
function mockApi(user:User=admin,items:Task[]=tasks){vi.spyOn(api,'me').mockResolvedValue(user);vi.spyOn(api,'tasks').mockResolvedValue({items,total:items.length,page:1,page_size:50});vi.spyOn(api,'summary').mockResolvedValue(summary({total_tasks:items.length}));vi.spyOn(api,'create').mockResolvedValue(task());vi.spyOn(api,'update').mockResolvedValue(task());vi.spyOn(api,'remove').mockResolvedValue();vi.spyOn(api,'logout').mockResolvedValue()}
async function renderApp(user:User=admin,items:Task[]=tasks,path='/app'){history.replaceState({},'',path);mockApi(user,items);const result=render(<App/>);await screen.findByText(user.name);if(items.length)await screen.findAllByText(items[0].title);return result}
describe('App autenticação e autorização',()=>{
  beforeEach(()=>{vi.setSystemTime(new Date('2026-09-20T12:00:00-03:00'))});
  it('mostra loading inicial e recupera sessão válida',async()=>{let resolve!:(value:User)=>void;vi.spyOn(api,'me').mockReturnValue(new Promise(r=>{resolve=r}));render(<App/>);expect(screen.getByText('Preparando seu fluxo…')).toBeInTheDocument();resolve(admin);expect(await screen.findByText('Admin Teste')).toBeInTheDocument();expect(location.pathname).toBe('/app')});
  it('mantém não autenticado no login e autentica via formulário',async()=>{history.replaceState({},'','/login');vi.spyOn(api,'me').mockRejectedValue(new ApiError('Não autenticado',401));vi.spyOn(api,'login').mockResolvedValue(admin);vi.spyOn(api,'tasks').mockResolvedValue({items:[],total:0,page:1,page_size:50});vi.spyOn(api,'summary').mockResolvedValue(summary({total_tasks:0}));render(<App/>);await userEvent.type(await screen.findByLabelText('E-mail'),'admin@test.com');await userEvent.type(screen.getByLabelText('Senha'),'password123');await userEvent.click(screen.getByRole('button',{name:'Entrar'}));expect(await screen.findByText('Admin Teste')).toBeInTheDocument();expect(location.pathname).toBe('/app')});
  it('sessão expirada remove área privada',async()=>{await renderApp();window.dispatchEvent(new Event('taskflow:unauthorized'));expect(await screen.findByRole('heading',{name:'Entre na sua conta'})).toBeInTheDocument();expect(screen.queryByText('Admin Teste')).not.toBeInTheDocument();expect(location.pathname).toBe('/login')});
  it('logout chama API e sempre limpa a interface',async()=>{await renderApp();await userEvent.click(screen.getByRole('button',{name:'Sair'}));expect(api.logout).toHaveBeenCalledOnce();expect(await screen.findByRole('heading',{name:'Entre na sua conta'})).toBeInTheDocument()});
  it('ADMIN vê navegação e controles de mutação',async()=>{const{container}=await renderApp();expect(screen.getByRole('button',{name:/Nova tarefa/})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Integrações'})).toBeInTheDocument();expect(screen.getAllByRole('button',{name:'Editar tarefa'})).toHaveLength(3);expect(screen.getAllByRole('button',{name:'Excluir tarefa'})).toHaveLength(3);expect(screen.getAllByRole('button',{name:/Concluir tarefa|Reabrir tarefa/})).toHaveLength(3);expect(await axe(container)).toHaveNoViolations()});
  it('abre e fecha o menu mobile por botões acessíveis',async()=>{await renderApp();await userEvent.click(screen.getByRole('button',{name:'Abrir menu'}));expect(document.querySelector('.app-shell aside')).toHaveClass('open');await userEvent.click(screen.getAllByRole('button',{name:'Fechar menu'})[0]);expect(document.querySelector('.app-shell aside')).not.toHaveClass('open')});
  it('MEMBER vê leituras, não controles nem conteúdo administrativo',async()=>{await renderApp(member,tasks,'/app?view=integrations');for(const label of ['Visão Geral','Todas as Tarefas','Próximas','Concluídas','Calendário','Estatísticas'])expect(screen.getByRole('button',{name:label})).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Integrações'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:/Nova tarefa/})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Editar tarefa'})).not.toBeInTheDocument();expect(screen.queryByText('Integração administrativa Google')).not.toBeInTheDocument();expect(screen.getByText(/Olá, Aluno/)).toBeInTheDocument()});
});
describe('App tarefas e visualizações',()=>{
  beforeEach(()=>vi.setSystemTime(new Date('2026-09-20T12:00:00-03:00')));
  it('busca é case-insensitive e mostra empty state',async()=>{await renderApp();const search=screen.getByLabelText('Buscar tarefa');await userEvent.type(search,'pYtHoN');expect(screen.getAllByText('Python')).not.toHaveLength(0);expect(screen.queryByText('Cálculo')).not.toBeInTheDocument();await userEvent.clear(search);await userEvent.type(search,'inexistente');expect(screen.getByText('Tudo limpo por aqui.')).toBeInTheDocument()});
  it('carrega filtros e todas as visualizações',async()=>{await renderApp();expect(screen.getByText('2 tarefas')).toBeInTheDocument();expect(screen.getByText('33%')).toBeInTheDocument();expect(document.querySelector('.metric-coral')).toHaveTextContent('2');await userEvent.click(screen.getByRole('button',{name:'Próximas'}));await waitFor(()=>expect(api.tasks).toHaveBeenLastCalledWith('?upcoming=true'));await userEvent.click(screen.getByRole('button',{name:'Concluídas'}));await waitFor(()=>expect(api.tasks).toHaveBeenLastCalledWith('?status=COMPLETED'));await userEvent.click(screen.getByRole('button',{name:'Todas as Tarefas'}));await waitFor(()=>expect(api.tasks).toHaveBeenLastCalledWith(''));await userEvent.click(screen.getByRole('button',{name:'Estatísticas'}));expect(screen.getByText('Por prioridade')).toBeInTheDocument();expect(screen.getByText('Programação')).toBeInTheDocument()});
  it('calendário preserva datas locais, múltiplas tarefas e navega anos',async()=>{await renderApp();await userEvent.click(screen.getByRole('button',{name:'Calendário'}));expect(screen.getByRole('heading',{name:/setembro de 2026/i})).toBeInTheDocument();const day20=[...document.querySelectorAll('.calendar-grid > div')].find(node=>node.querySelector('span')?.textContent==='20')!;expect(within(day20 as HTMLElement).getByText('Cálculo')).toBeInTheDocument();expect(within(day20 as HTMLElement).getByText('Python')).toBeInTheDocument();expect(screen.queryByText('Álgebra')).not.toBeInTheDocument();expect(day20).toHaveClass('today');await userEvent.click(screen.getByRole('button',{name:'Próximo mês'}));expect(screen.getByRole('heading',{name:/outubro de 2026/i})).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Mês anterior'}));expect(screen.getByRole('heading',{name:/setembro de 2026/i})).toBeInTheDocument()});
  it('calendário atravessa dezembro/janeiro e funciona vazio',async()=>{vi.setSystemTime(new Date('2026-12-10T12:00:00'));await renderApp(admin,[]);await userEvent.click(screen.getByRole('button',{name:'Calendário'}));await userEvent.click(screen.getByRole('button',{name:'Próximo mês'}));expect(screen.getByRole('heading',{name:/janeiro de 2027/i})).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Mês anterior'}));await userEvent.click(screen.getByRole('button',{name:'Mês anterior'}));expect(screen.getByRole('heading',{name:/novembro de 2026/i})).toBeInTheDocument();expect(document.querySelectorAll('.has-tasks')).toHaveLength(0)});
  it('cria e edita tarefa atualizando a lista',async()=>{await renderApp();await userEvent.click(screen.getByRole('button',{name:/Nova tarefa/}));await userEvent.type(screen.getByLabelText('Título'),'Nova tarefa');await userEvent.type(screen.getByLabelText('Categoria'),'Testes');await userEvent.click(screen.getByRole('button',{name:'Salvar tarefa'}));await waitFor(()=>expect(api.create).toHaveBeenCalledWith(expect.objectContaining({title:'Nova tarefa',category:'Testes'})));await userEvent.click(screen.getAllByRole('button',{name:'Editar tarefa'})[0]);expect(screen.getByLabelText('Título')).toHaveValue('Cálculo');await userEvent.clear(screen.getByLabelText('Título'));await userEvent.type(screen.getByLabelText('Título'),'Cálculo II');await userEvent.click(screen.getByRole('button',{name:'Salvar tarefa'}));await waitFor(()=>expect(api.update).toHaveBeenCalledWith(1,expect.objectContaining({title:'Cálculo II'})))});
  it('conclui, reabre e trata falha de PATCH',async()=>{await renderApp();await userEvent.click(screen.getAllByRole('button',{name:'Concluir tarefa'})[0]);await waitFor(()=>expect(api.update).toHaveBeenCalledWith(1,{status:'COMPLETED'}));await waitFor(()=>screen.getByRole('button',{name:'Reabrir tarefa'}));await userEvent.click(screen.getByRole('button',{name:'Reabrir tarefa'}));await waitFor(()=>expect(api.update).toHaveBeenCalledWith(3,{status:'PENDING'}));await waitFor(()=>screen.getAllByRole('button',{name:'Concluir tarefa'})[0]);vi.mocked(api.update).mockRejectedValueOnce(new Error('PATCH indisponível'));await userEvent.click(screen.getAllByRole('button',{name:'Concluir tarefa'})[0]);expect(await screen.findByRole('alert')).toHaveTextContent('PATCH indisponível')});
  it('cancela e confirma exclusão, tratando falha',async()=>{await renderApp();vi.stubGlobal('confirm',vi.fn().mockReturnValueOnce(false).mockReturnValueOnce(true).mockReturnValueOnce(true));let remove=screen.getAllByRole('button',{name:'Excluir tarefa'})[0];await userEvent.click(remove);expect(api.remove).not.toHaveBeenCalled();await userEvent.click(remove);expect(api.remove).toHaveBeenCalledWith(1);remove=await waitFor(()=>screen.getAllByRole('button',{name:'Excluir tarefa'})[0]);vi.mocked(api.remove).mockRejectedValueOnce(new Error('DELETE indisponível'));await userEvent.click(remove);expect(await screen.findByRole('alert')).toHaveTextContent('DELETE indisponível')});
  it('mostra falha de carregamento e permite fechar aviso',async()=>{history.replaceState({},'','/app');mockApi();vi.mocked(api.tasks).mockRejectedValue(new Error('API indisponível'));render(<App/>);expect(await screen.findByRole('alert')).toHaveTextContent('API indisponível');await userEvent.click(screen.getByRole('button',{name:'Fechar aviso'}));expect(screen.queryByRole('alert')).not.toBeInTheDocument()});
});
